server:
  port: 9935
spring:  mvc:    view:      prefix: /views/      suffix: .jsp
  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: systema
    password: root
  jpa:
    show-sql: true
    hibernate:      ddl-auto: update
      
    